### ISSUE TITLE
Short description clarification

### ISSUE THREAD

**Issue by AbdealiLoKo** [bnosac/spark.sas7bdat#2]
It would be good to modify the short description of the repository from:

Read in SAS data in parallel into Apache Spark

To:

R library to read SAS data in parallel into Apache Spark
or
R library to read SAS data in parallel into Apache Spark (using spark-sas7bdat)

or similar, as this is specifically for R and caused a bit of confusion for me as I thought it was a replacement for spark-sas7bdat for a while (Until I properly read the readme and found it actually uses spark-sas7bdat)

**Comment by jwijffels** [comment]
Feel free to make a pull request
